In [23]:
# NumPyをインポート
import numpy as np

# NumPyの多次元配列
multi_array = np.array([[0, 1], [2, 3], [4, 5], [6, 7]])
multi_array

# 行列の積の計算
A = np.array([[0, 1], [2, 3], [4, 5]])
B = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

# 計算結果を表示する
print(np.dot(A, B))

# 行列の要素の最大値
np.dot(A, B).max()

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]


47